# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 620a1a7227cbfa6eda681e4e2b53b84bf33aa4031d52bb278aae5558f4b6ec052fd3cd9e4146c3b03f1af0a9e72bb98d80b20296cb66692991f99cf852279065

test:
  secret_key_base: 8b1ceb3309587967c80d3b2bafc88d2485a86f6564a6dc4902fe5f19007722ae70b49fdf5d1d4169eea1deb3767170ebfb91395e395fca8f632f5ccf1242afc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
